development:
  gst: /Users/rydikov/Downloads/video.mp4 
  stills_dir: /Users/rydikov/Projects/Other/RASPBERRY/Stills

production:
  gst: uridecodebin uri=rtsp://***REMOVED***@192.168.1.64:554/Streaming/Channels/101 ! videoconvert ! video/x-raw ! appsink drop=true
  stills_dir: /home/pi/timelapse/Stills