development:
  gst: ../demo.mov 
  stills_dir: /Users/rydikov/Projects/Other/RASPBERRY/Stills
  model_path: ..
  device_name: CPU

production:
  gst: uridecodebin uri=rtsp://***REMOVED***@192.168.1.64:554/Streaming/Channels/101 ! videoconvert ! video/x-raw ! appsink max-buffers=1 drop=true
  stills_dir: /home/pi/timelapse/Stills
  model_path: /home/pi
  device_name: MYRIAD