development:
  source: rtsp://admin:w1NCyp2eKVCc3Da9Ab4p@192.168.254.14:554/cam/realmonitor?channel=1&subtype=0
  stills_dir: /Users/rydikov/Projects/Other/RASPBERRY/Stills
  model_path: ..
  device_name: CPU

production:
  source: rtsp://***REMOVED***@192.168.1.64:554/Streaming/Channels/101
  stills_dir: /home/pi/timelapse/Stills
  model_path: /home/pi/yolo
  device_name: MYRIAD