development:
  source: /Users/rydikov/Projects/Other/RASPBERRY/demo.mov
  stills_dir: /Users/rydikov/Projects/Other/RASPBERRY/Stills
  model_path: /Users/rydikov/Projects/Other/RASPBERRY/
  device_name: CPU
  host_stills_dir: http://localhost
  telegram_bot_token: 1235420589:AAHWrwEGduTzg98Sah4EOjZYxFzFRUre1Eg
  telegram_bot_chat_id: 53757246

production:
  source: rtspsrc location=rtsp://***REMOVED***@192.168.1.64:554/Streaming/Channels/101 debug=true latency=100 rtp-blocksize=65536 drop-on-latency=true protocols=GST_RTSP_LOWER_TRANS_TCP do-retransmission=false ! decodebin ! videoconvert ! appsink max-buffers=1 drop=true
  stills_dir: /home/pi/timelapse/Stills
  model_path: /home/pi/yolo
  device_name: MYRIAD
  host_stills_dir: https://web.rydikov-home.keenetic.pro
  telegram_bot_token: 1235420589:AAHWrwEGduTzg98Sah4EOjZYxFzFRUre1Eg
  telegram_bot_chat_id: 53757246